scan_filter_chain:
- name: box_standing_floor
  type: LaserScanBoxFilter
  params:
    box_frame: ring
    min_x: -1.8
    max_x: 1.8
    min_y: -1.8
    max_y: 1.8
    min_z: 0.05
    max_z: 0.25
- name: box_standing_roof
  type: LaserScanBoxFilter
  params:
    box_frame: ring
    min_x: -1.8
    max_x: 1.8
    min_y: -1.8
    max_y: 1.8
    min_z: 0.8
    max_z: 2.0
