scan_filter_chain:
- name: shadows
  type: ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 170
    neighbors: 20
    window: 1
- name: box
  type: LaserScanBoxFilter
  params:
    box_frame: leg_l_toe_center
    min_x: -0.09
    max_x: 0.09
    min_y: -0.07
    max_y: 0.07
    min_z: -0.1
    max_z: 0.3

