scan_filter_chain:
- name: shadows
  type: ScanShadowsFilter
  params:
    min_angle: 5
    max_angle: 175
    neighbors: 20
    window: 1
- name: box
  type: LaserScanBoxFilter
  params:
    box_frame: leg_r_toe_center
    min_x: -0.09
    max_x: 0.09
    min_y: -0.05
    max_y: 0.05
    min_z: -0.1
    max_z: 0.3