scan_filter_chain:
- name: shadows
  type: ScanShadowsFilter
  params:
    min_angle: 5
    max_angle: 175
    neighbors: 3
    window: 1
- name: box_toe
  type: LaserScanBoxFilter
  params:
    box_frame: leg_l_toe_center
    min_x: -0.09
    max_x: 0.09
    min_y: -0.07
    max_y: 0.07
    min_z: -0.1
    max_z: 0.3
- name: box_knee
  type: LaserScanBoxFilter
  params:
    box_frame: leg_l_link3
    min_x: -0.2
    max_x: 0.04
    min_y: -0.02
    max_y: 0.07
    min_z: -0.2
    max_z: 0.2
