
gazebo_dc_motor:
  motor_characteristics:
    #body
    chest_joint01:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    #leg right
    leg_r_joint01:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    leg_r_joint02:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    leg_r_joint03:
      motor_model_type: Voltage
      stall_effort: 11.0
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    leg_r_joint04:
      motor_model_type: Voltage
      stall_effort: 11.0
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    leg_r_joint11:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    leg_r_joint12:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    #leg left
    leg_l_joint01:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    leg_l_joint02:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    leg_l_joint03:
      motor_model_type: Voltage
      stall_effort: 11.0
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    leg_l_joint04:
      motor_model_type: Voltage
      stall_effort: 11.0
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    leg_l_joint11:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    leg_l_joint12:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    #arm right
    arm_r_joint01:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    arm_r_joint02:
      motor_model_type: Voltage
      stall_effort: 11.0
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    arm_r_joint03:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    arm_r_joint04:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    #arm left
    arm_l_joint01:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    arm_l_joint02:
      motor_model_type: Voltage
      stall_effort: 11.0
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    arm_l_joint03:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    arm_l_joint04:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
