
gazebo_dc_motor:
  motor_characteristics:
    #body
    chest_joint01:
      motor_model_type: Voltage
      stall_effort: 5.50
      noload_speed: 4.76
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
