
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

# Position Controllers ---------------------------------------
chest_joint01_position_controller:
  type: position_controllers/JointPositionController
  joint: chest_joint01
leg_r_joint04_position_controller:
  type: position_controllers/JointPositionController
  joint: leg_r_joint04
