subscribers:

  camera_reading:
    topic: /remote/decompress/rgb_decompress
    queue_size: 1

actions:

  camera_reading:
    name: /remote/darknet_ros/check_for_objects

publishers:

  object_detector:
    topic: /remote/darknet_ros/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /remote/darknet_ros/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /remote/darknet_ros/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true
