
gazebo_ros_control:
  pid_gains:
    #body
    body_joint1:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    #arm right
    arm_r_joint0:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    arm_r_joint1:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    arm_r_joint2:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    arm_r_joint3:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    #arm left
    arm_l_joint0:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    arm_l_joint1:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    arm_l_joint2:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    arm_l_joint3:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true

    #arm right
    leg_r_joint0:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    leg_r_joint1:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    leg_r_joint4:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    leg_r_joint7:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    leg_r_joint8:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    #arm left
    leg_l_joint0:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    leg_l_joint1:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    leg_l_joint4:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    leg_l_joint7:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    leg_l_joint8:
      p: 0.15
      i: 0.0
      d: 0.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
