
gazebo_dc_motor:
  motor_characteristics:
    #leg right
    leg_r_joint03:
      motor_model_type: Voltage
      stall_effort: 10.6
      noload_speed: 3.14
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    leg_r_joint04:
      motor_model_type: Voltage
      stall_effort: 10.6
      noload_speed: 3.14
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    #leg left
    leg_l_joint03:
      motor_model_type: Voltage
      stall_effort: 10.6
      noload_speed: 3.14
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    leg_l_joint04:
      motor_model_type: Voltage
      stall_effort: 10.6
      noload_speed: 3.14
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    #arm right
    arm_r_joint02:
      motor_model_type: Voltage
      stall_effort: 10.6
      noload_speed: 3.14
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
    #arm left
    arm_l_joint02:
      motor_model_type: Voltage
      stall_effort: 10.6
      noload_speed: 3.14
      back_emf_lpf_time_constant: 0.0
      out_torque_lpf_time_constant: 0.0
